const moment = require('moment');
const axios = require('axios');
const {google}= require('googleapis');
const key = require('./keys.json');
const myInterval = setInterval(main, 120000);//for 10 min 60000

const client = new google.auth.JWT(
    key.client_email,
    null,
    key.private_key,
    ['https://www.googleapis.com/auth/spreadsheets'] // scope of the app https://developers.google.com/identity/protocols/oauth2/scopes#sheets
);
client.authorize(function(err,tokens){
    if(err){
        console.log(err);
        return;
    }else{
        console.log('connected!')
    }
});

async function main() {
    console.log("Main Started");
    const options = {
        method: 'GET',url: 'https://apidojo-yahoo-finance-v1.p.rapidapi.com/market/v2/get-quotes',
        params: {
            region: 'IN',
            symbols: 'TCS.NS, ONGC.NS, BAJAJFINSV.NS, UPL.NS, BAJFINANCE.NS, SBILIFE.NS, BPCL.NS, ITC.NS, HINDALCO.NS, JSWSTEEL.NS,BAJAJ-AUTO.NS, KOTAKBANK.NS, COALINDIA.NS, M&M.NS, TATAMOTORS.NS, INFY.NS, EICHERMOT.NS, TATASTEEL.NS, TECHM.NS, RELIANCE.NS, NESTLEIND.NS, INDUSINDBK.NS, LT.NS, BRITANNIA.NS,BHARTIARTL.NS, ULTRACEMCO.NS, DRREDDY.NS, HCLTECH.NS, TATACONSUM.NS, ADANIENT.NS, HEROMOTOCO.NS, HDFCBANK.NS, WIPRO.NS, NTPC.NS, MARUTI.NS,TITAN.NS,DIVISLAB.NS,ICICIBANK.NS,ADANIPORTS.NS,HDFC.NS,ASIANPAINT.NS,CIPLA.NS,AXISBANK.NS,SBIN.NS,GRASIM.NS,SUNPHARMA.NS,APOLLOHOSP.NS,HINDUNILVR.NS,POWERGRID.NS,HDFCLIFE.NS'
        },headers: {
            'X-RapidAPI-Key': 'c6e48adc6dmsh05900b13b361ae0p17f651jsn7a03c8e8b550',
            'X-RapidAPI-Host': 'apidojo-yahoo-finance-v1.p.rapidapi.com'
        }
    }
    const response = await axios.request(options);
    const Data = response.data

let data1 = {SYMBOL:Data['quoteResponse']['result'][0]['shortName'],LTP: Data['quoteResponse']['result'][0]['regularMarketPrice'],CHNG:Data['quoteResponse']['result'][0]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][0]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][0]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][0]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][0]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][0]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][0]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][0]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][0]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data2 = {SYMBOL:Data['quoteResponse']['result'][1]['shortName'],LTP: Data['quoteResponse']['result'][1]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][1]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][1]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][1]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][1]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][1]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][1]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][1]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][1]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][1]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data3 = {SYMBOL:Data['quoteResponse']['result'][2]['shortName'],LTP: Data['quoteResponse']['result'][2]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][2]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][2]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][2]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][2]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][2]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][2]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][2]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][2]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][2]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data4 = {SYMBOL:Data['quoteResponse']['result'][3]['shortName'],LTP: Data['quoteResponse']['result'][3]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][3]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][3]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][3]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][3]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][3]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][3]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][3]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][3]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][3]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data5 = {SYMBOL:Data['quoteResponse']['result'][4]['shortName'],LTP: Data['quoteResponse']['result'][4]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][4]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][4]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][4]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][4]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][4]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][4]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][4]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][4]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][4]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data6 = {SYMBOL:Data['quoteResponse']['result'][5]['shortName'],LTP: Data['quoteResponse']['result'][5]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][5]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][5]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][5]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][5]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][5]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][5]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][5]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][5]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][5]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data7 = {SYMBOL:Data['quoteResponse']['result'][6]['shortName'],LTP: Data['quoteResponse']['result'][6]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][6]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][6]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][6]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][6]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][6]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][6]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][6]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][6]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][6]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data8 = {SYMBOL:Data['quoteResponse']['result'][7]['shortName'],LTP: Data['quoteResponse']['result'][7]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][7]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][7]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][7]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][7]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][7]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][7]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][7]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][7]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][7]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data9 = {SYMBOL:Data['quoteResponse']['result'][8]['shortName'],LTP: Data['quoteResponse']['result'][8]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][8]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][8]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][8]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][8]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][8]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][8]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][8]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][8]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][8]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data10= {SYMBOL:Data['quoteResponse']['result'][9]['shortName'],LTP: Data['quoteResponse']['result'][9]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][9]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][9]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][9]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][9]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][9]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][9]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][9]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][9]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][9]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data11= {SYMBOL:Data['quoteResponse']['result'][10]['shortName'],LTP: Data['quoteResponse']['result'][10]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][10]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][10]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][10]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][10]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][10]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][10]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][10]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][10]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][10]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data12= {SYMBOL:Data['quoteResponse']['result'][11]['shortName'],LTP: Data['quoteResponse']['result'][11]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][11]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][11]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][11]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][11]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][11]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][11]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][11]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][11]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][11]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data13= {SYMBOL:Data['quoteResponse']['result'][12]['shortName'],LTP: Data['quoteResponse']['result'][12]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][12]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][12]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][12]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][12]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][12]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][12]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][12]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][12]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][12]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data14= {SYMBOL:Data['quoteResponse']['result'][13]['shortName'],LTP: Data['quoteResponse']['result'][13]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][13]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][13]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][13]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][13]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][13]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][13]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][13]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][13]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][13]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data15= {SYMBOL:Data['quoteResponse']['result'][14]['shortName'],LTP: Data['quoteResponse']['result'][14]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][14]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][14]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][14]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][14]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][14]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][14]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][14]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][14]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][14]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data16= {SYMBOL:Data['quoteResponse']['result'][15]['shortName'],LTP: Data['quoteResponse']['result'][15]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][15]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][15]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][15]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][15]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][15]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][15]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][15]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][15]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][15]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data17= {SYMBOL:Data['quoteResponse']['result'][16]['shortName'],LTP: Data['quoteResponse']['result'][16]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][16]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][16]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][16]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][16]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][16]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][16]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][16]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][16]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][16]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data18= {SYMBOL:Data['quoteResponse']['result'][17]['shortName'],LTP: Data['quoteResponse']['result'][17]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][17]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][17]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][17]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][17]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][17]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][17]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][17]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][17]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][17]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data19= {SYMBOL:Data['quoteResponse']['result'][18]['shortName'],LTP: Data['quoteResponse']['result'][18]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][18]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][18]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][18]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][18]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][18]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][18]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][18]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][18]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][18]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data20= {SYMBOL:Data['quoteResponse']['result'][19]['shortName'],LTP: Data['quoteResponse']['result'][19]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][19]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][19]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][19]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][19]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][19]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][19]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][19]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][19]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][19]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data21= {SYMBOL:Data['quoteResponse']['result'][20]['shortName'],LTP: Data['quoteResponse']['result'][20]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][20]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][20]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][20]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][20]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][20]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][20]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][20]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][20]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][20]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data22= {SYMBOL:Data['quoteResponse']['result'][21]['shortName'],LTP: Data['quoteResponse']['result'][21]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][21]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][21]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][21]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][21]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][21]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][21]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][21]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][21]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][21]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data23= {SYMBOL:Data['quoteResponse']['result'][22]['shortName'],LTP: Data['quoteResponse']['result'][22]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][22]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][22]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][22]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][22]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][22]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][22]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][22]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][22]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][22]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data24= {SYMBOL:Data['quoteResponse']['result'][23]['shortName'],LTP: Data['quoteResponse']['result'][23]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][23]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][23]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][23]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][23]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][23]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][23]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][23]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][23]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][23]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data25= {SYMBOL:Data['quoteResponse']['result'][24]['shortName'],LTP: Data['quoteResponse']['result'][24]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][24]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][24]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][24]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][24]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][24]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][24]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][24]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][24]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][24]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data26= {SYMBOL:Data['quoteResponse']['result'][25]['shortName'],LTP: Data['quoteResponse']['result'][25]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][25]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][25]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][25]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][25]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][25]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][25]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][25]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][25]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][25]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data27= {SYMBOL:Data['quoteResponse']['result'][26]['shortName'],LTP: Data['quoteResponse']['result'][26]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][26]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][26]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][26]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][26]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][26]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][26]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][26]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][26]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][26]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data28= {SYMBOL:Data['quoteResponse']['result'][27]['shortName'],LTP: Data['quoteResponse']['result'][27]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][27]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][27]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][27]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][27]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][27]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][27]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][27]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][27]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][27]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data29= {SYMBOL:Data['quoteResponse']['result'][28]['shortName'],LTP: Data['quoteResponse']['result'][28]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][28]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][28]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][28]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][28]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][28]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][28]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][28]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][28]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][28]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data30= {SYMBOL:Data['quoteResponse']['result'][29]['shortName'],LTP: Data['quoteResponse']['result'][29]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][29]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][29]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][29]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][29]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][29]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][29]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][29]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][29]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][29]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data31= {SYMBOL:Data['quoteResponse']['result'][33]['shortName'],LTP: Data['quoteResponse']['result'][33]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][33]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][33]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][33]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][33]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][33]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][33]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][33]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][33]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][33]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data32= {SYMBOL:Data['quoteResponse']['result'][31]['shortName'],LTP: Data['quoteResponse']['result'][31]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][31]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][31]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][31]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][31]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][31]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][31]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][31]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][31]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][31]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data33= {SYMBOL:Data['quoteResponse']['result'][32]['shortName'],LTP: Data['quoteResponse']['result'][32]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][32]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][32]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][32]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][32]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][32]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][32]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][32]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][32]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][32]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data34= {SYMBOL:Data['quoteResponse']['result'][33]['shortName'],LTP: Data['quoteResponse']['result'][33]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][33]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][33]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][33]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][33]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][33]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][33]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][33]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][33]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][33]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data35= {SYMBOL:Data['quoteResponse']['result'][34]['shortName'],LTP: Data['quoteResponse']['result'][34]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][34]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][34]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][34]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][34]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][34]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][34]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][34]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][34]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][34]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data36= {SYMBOL:Data['quoteResponse']['result'][35]['shortName'],LTP: Data['quoteResponse']['result'][35]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][35]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][35]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][35]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][35]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][35]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][35]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][35]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][35]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][35]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data37= {SYMBOL:Data['quoteResponse']['result'][36]['shortName'],LTP: Data['quoteResponse']['result'][36]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][36]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][36]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][36]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][36]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][36]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][36]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][36]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][36]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][36]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data38= {SYMBOL:Data['quoteResponse']['result'][37]['shortName'],LTP: Data['quoteResponse']['result'][37]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][37]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][37]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][37]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][37]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][37]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][37]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][37]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][37]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][37]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data39= {SYMBOL:Data['quoteResponse']['result'][38]['shortName'],LTP: Data['quoteResponse']['result'][38]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][38]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][38]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][38]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][38]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][38]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][38]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][38]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][38]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][38]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data40= {SYMBOL:Data['quoteResponse']['result'][39]['shortName'],LTP: Data['quoteResponse']['result'][39]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][39]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][39]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][39]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][39]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][39]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][39]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][39]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][39]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][39]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data41= {SYMBOL:Data['quoteResponse']['result'][40]['shortName'],LTP: Data['quoteResponse']['result'][40]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][40]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][40]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][40]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][40]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][40]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][40]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][40]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][40]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][40]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data42= {SYMBOL:Data['quoteResponse']['result'][41]['shortName'],LTP: Data['quoteResponse']['result'][41]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][41]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][41]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][41]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][41]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][41]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][41]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][41]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][41]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][41]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data43= {SYMBOL:Data['quoteResponse']['result'][42]['shortName'],LTP: Data['quoteResponse']['result'][42]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][42]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][42]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][42]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][42]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][42]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][42]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][42]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][42]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][42]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data44= {SYMBOL:Data['quoteResponse']['result'][43]['shortName'],LTP: Data['quoteResponse']['result'][43]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][43]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][43]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][43]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][43]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][43]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][43]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][43]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][43]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][43]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data45= {SYMBOL:Data['quoteResponse']['result'][44]['shortName'],LTP: Data['quoteResponse']['result'][44]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][44]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][44]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][44]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][44]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][44]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][44]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][44]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][44]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][44]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data46= {SYMBOL:Data['quoteResponse']['result'][45]['shortName'],LTP: Data['quoteResponse']['result'][45]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][45]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][45]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][45]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][45]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][45]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][45]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][45]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][45]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][45]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data47= {SYMBOL:Data['quoteResponse']['result'][46]['shortName'],LTP: Data['quoteResponse']['result'][46]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][46]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][46]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][46]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][46]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][46]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][46]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][46]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][46]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][46]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data48= {SYMBOL:Data['quoteResponse']['result'][47]['shortName'],LTP: Data['quoteResponse']['result'][47]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][47]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][47]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][47]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][47]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][47]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][47]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][47]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][47]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][47]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data49= {SYMBOL:Data['quoteResponse']['result'][48]['shortName'],LTP: Data['quoteResponse']['result'][48]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][48]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][48]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][48]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][48]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][48]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][48]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][48]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][48]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][48]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}
let data50= {SYMBOL:Data['quoteResponse']['result'][49]['shortName'],LTP: Data['quoteResponse']['result'][49]['regularMarketPrice'],CHNG: Data['quoteResponse']['result'][49]['regularMarketChange'],CHANGPercentage: parseFloat(Data['quoteResponse']['result'][49]['regularMarketChangePercent'].toFixed(2)),OPEN: Data['quoteResponse']['result'][49]['regularMarketOpen'],HIGH:Data['quoteResponse']['result'][49]['regularMarketDayHigh'],LOW:Data['quoteResponse']['result'][49]['regularMarketDayLow'],VOLUME:Data['quoteResponse']['result'][49]['regularMarketVolume'],fiftyTwo_WL:Data['quoteResponse']['result'][49]['fiftyTwoWeekLow'],fiftyTwo_WH:Data['quoteResponse']['result'][49]['fiftyTwoWeekHigh'],PREVCLOSE:Data['quoteResponse']['result'][49]['regularMarketPreviousClose'],Date:moment().format('DD-MM-YY'),Time:moment().format('hh.mm')}

// console.log(data1);
        let data = JSON.stringify({
        data1,data2,data3,data4,data5,data6,data7,data8,data9,data10,
        data11,data12,data13,data14,data15,data16,data17,data18,data19,data20,
        data21, data22,data23,data24,data25,data26,data27,data28,data29,data30, 
        data31,data32,data33,data34,data35,data36,data37,data38,data39,data40, 
        data41,data42,data43,data44,data45,data46,data47,data48,data49,data50
    });
    // console.log(data);
    let config = {
    method: 'post',
    maxBodyLength: Infinity,
    url: 'https://api.niftyleveltracker.in/App/api/v1/scrapData',//https://api.niftyleveltracker.in/App/api/v1/scrapData, Local: http://localhost:8000/App/api/v1/scrapData
    headers: { 
        'Content-Type': 'application/json'
        },
    data : data
    };
    axios.request(config)
    .then((response) => {
        covert(response.data,0)
    })
    .catch(async(error) => {
    console.log('Internet Speed Is SLOW',error);
    });
    console.log("113: Post request");
    console.log('114: Stocks Post Successfully');
    
}
 //Inserting data  into sheet 1
async function gsRun(client,stocks){
    const gsApi = google.sheets({version:'v4',auth:client});

//Insert data in to  sheet 1 //
    const updateOption= {
        spreadsheetId:'1iA8gKAehpYPaI8XMb5PhE6dFs0HTxNohZQHizScRk84', // spreadsheetId
        range: 'Data!A2',
        valueInputOption:'USER_ENTERED',
        resource: {values:stocks}
    };
    let res = await gsApi.spreadsheets.values.update(updateOption); // post
    console.log(res.status);    
    const date =moment().format('DD-MM-YY')
    const time = moment().subtract(10,"m").format('hh.mm')
      //Get Data for Sheet 2//
let data = '';

let config = {
    method: 'get',
    maxBodyLength: Infinity,
    url: 'https://api.niftyleveltracker.in/App/api/v1/getScrapData/',//https://api.niftyleveltracker.in/App/api/v1/getScrapData/, LOcal: 'http://localhost:8000/App/api/v1/getScrapData/
    headers: {date:date.toString(),time: time.toString()},
    data : data
};

axios.request(config)
.then((response) => {
    // console.log(`597: Get request for sheet 2 with time ${time}`)
    covert(response.data,1)
})
.catch((error) => {
    console.log('149:',error.response.data.message);
});
// Sheet 2 //

  //Get Data for Sheet 3//
    const time1 = moment().subtract(20,"m").format('hh.mm')
    let dataA = '';

let configA = {
    method: 'get',
    maxBodyLength: Infinity,
    url: 'https://api.niftyleveltracker.in/App/api/v1/getScrapData20',//http://localhost:8000/App/api/v1/getScrapData20
    headers: { date:date.toString(),time1: time1.toString()},
    data : dataA
};

axios.request(configA)
.then((response) => {
    console.log(`167: Get request for sheet 3 with time ${time1}`);
    covert(response.data,2)
})
.catch((error) => {
    console.log('171:',error.response.data.message);
});
// Sheet 3//


};
function covert(data,funcNu){
    try {
        // resData =data[50]
        // console.log(resData);
        let GetStock = []
        console.log("182: Data converted >>>")
        GetStock.push([data[0].SYMBOL,data[0].OPEN,data[0].HIGH,data[0].LOW,data[0].PREVCLOSE,data[0].LTP,data[0].CHNG,data[0].CHANGPercentage,data[0].VOLUME,data[0].fiftyTwo_WH,data[0].fiftyTwo_WL,data[0].Date,data[0].Time]);
        GetStock.push([data[1].SYMBOL,data[1].OPEN,data[1].HIGH,data[1].LOW,data[1].PREVCLOSE,data[1].LTP,data[1].CHNG,data[1].CHANGPercentage,data[1].VOLUME,data[1].fiftyTwo_WH,data[1].fiftyTwo_WL,data[1].Date,data[1].Time]);
        GetStock.push([data[2].SYMBOL,data[2].OPEN,data[2].HIGH,data[2].LOW,data[2].PREVCLOSE,data[2].LTP,data[2].CHNG,data[2].CHANGPercentage,data[2].VOLUME,data[2].fiftyTwo_WH,data[2].fiftyTwo_WL,data[2].Date,data[2].Time]);
        GetStock.push([data[3].SYMBOL,data[3].OPEN,data[3].HIGH,data[3].LOW,data[3].PREVCLOSE,data[3].LTP,data[3].CHNG,data[3].CHANGPercentage,data[3].VOLUME,data[3].fiftyTwo_WH,data[3].fiftyTwo_WL,data[3].Date,data[3].Time]);
        GetStock.push([data[4].SYMBOL,data[4].OPEN,data[4].HIGH,data[4].LOW,data[4].PREVCLOSE,data[4].LTP,data[4].CHNG,data[4].CHANGPercentage,data[4].VOLUME,data[4].fiftyTwo_WH,data[4].fiftyTwo_WL,data[4].Date,data[4].Time]);
        GetStock.push([data[5].SYMBOL,data[5].OPEN,data[5].HIGH,data[5].LOW,data[5].PREVCLOSE,data[5].LTP,data[5].CHNG,data[5].CHANGPercentage,data[5].VOLUME,data[5].fiftyTwo_WH,data[5].fiftyTwo_WL,data[5].Date,data[5].Time]);
        GetStock.push([data[6].SYMBOL,data[6].OPEN,data[6].HIGH,data[6].LOW,data[6].PREVCLOSE,data[6].LTP,data[6].CHNG,data[6].CHANGPercentage,data[6].VOLUME,data[6].fiftyTwo_WH,data[6].fiftyTwo_WL,data[6].Date,data[6].Time]);
        GetStock.push([data[7].SYMBOL,data[7].OPEN,data[7].HIGH,data[7].LOW,data[7].PREVCLOSE,data[7].LTP,data[7].CHNG,data[7].CHANGPercentage,data[7].VOLUME,data[7].fiftyTwo_WH,data[7].fiftyTwo_WL,data[7].Date,data[7].Time]);
        GetStock.push([data[8].SYMBOL,data[8].OPEN,data[8].HIGH,data[8].LOW,data[8].PREVCLOSE,data[8].LTP,data[8].CHNG,data[8].CHANGPercentage,data[8].VOLUME,data[8].fiftyTwo_WH,data[8].fiftyTwo_WL,data[8].Date,data[8].Time]);
        GetStock.push([data[9].SYMBOL,data[9].OPEN,data[9].HIGH,data[9].LOW,data[9].PREVCLOSE,data[9].LTP,data[9].CHNG,data[9].CHANGPercentage,data[9].VOLUME,data[9].fiftyTwo_WH,data[9].fiftyTwo_WL,data[9].Date,data[9].Time]);
        GetStock.push([data[10].SYMBOL,data[10].OPEN,data[10].HIGH,data[10].LOW,data[10].PREVCLOSE,data[10].LTP,data[10].CHNG,data[10].CHANGPercentage,data[10].VOLUME,data[10].fiftyTwo_WH,data[10].fiftyTwo_WL,data[10].Date,data[10].Time]);
        GetStock.push([data[11].SYMBOL,data[11].OPEN,data[11].HIGH,data[11].LOW,data[11].PREVCLOSE,data[11].LTP,data[11].CHNG,data[11].CHANGPercentage,data[11].VOLUME,data[11].fiftyTwo_WH,data[11].fiftyTwo_WL,data[11].Date,data[11].Time]);
        GetStock.push([data[12].SYMBOL,data[12].OPEN,data[12].HIGH,data[12].LOW,data[12].PREVCLOSE,data[12].LTP,data[12].CHNG,data[12].CHANGPercentage,data[12].VOLUME,data[12].fiftyTwo_WH,data[12].fiftyTwo_WL,data[12].Date,data[12].Time]);
        GetStock.push([data[13].SYMBOL,data[13].OPEN,data[13].HIGH,data[13].LOW,data[13].PREVCLOSE,data[13].LTP,data[13].CHNG,data[13].CHANGPercentage,data[13].VOLUME,data[13].fiftyTwo_WH,data[13].fiftyTwo_WL,data[13].Date,data[13].Time]);
        GetStock.push([data[14].SYMBOL,data[14].OPEN,data[14].HIGH,data[14].LOW,data[14].PREVCLOSE,data[14].LTP,data[14].CHNG,data[14].CHANGPercentage,data[14].VOLUME,data[14].fiftyTwo_WH,data[14].fiftyTwo_WL,data[14].Date,data[14].Time]);
        GetStock.push([data[15].SYMBOL,data[15].OPEN,data[15].HIGH,data[15].LOW,data[15].PREVCLOSE,data[15].LTP,data[15].CHNG,data[15].CHANGPercentage,data[15].VOLUME,data[15].fiftyTwo_WH,data[15].fiftyTwo_WL,data[15].Date,data[15].Time]);
        GetStock.push([data[16].SYMBOL,data[16].OPEN,data[16].HIGH,data[16].LOW,data[16].PREVCLOSE,data[16].LTP,data[16].CHNG,data[16].CHANGPercentage,data[16].VOLUME,data[16].fiftyTwo_WH,data[16].fiftyTwo_WL,data[16].Date,data[16].Time]);
        GetStock.push([data[17].SYMBOL,data[17].OPEN,data[17].HIGH,data[17].LOW,data[17].PREVCLOSE,data[17].LTP,data[17].CHNG,data[17].CHANGPercentage,data[17].VOLUME,data[17].fiftyTwo_WH,data[17].fiftyTwo_WL,data[17].Date,data[17].Time]);
        GetStock.push([data[18].SYMBOL,data[18].OPEN,data[18].HIGH,data[18].LOW,data[18].PREVCLOSE,data[18].LTP,data[18].CHNG,data[18].CHANGPercentage,data[18].VOLUME,data[18].fiftyTwo_WH,data[18].fiftyTwo_WL,data[18].Date,data[18].Time]);
        GetStock.push([data[19].SYMBOL,data[19].OPEN,data[19].HIGH,data[19].LOW,data[19].PREVCLOSE,data[19].LTP,data[19].CHNG,data[19].CHANGPercentage,data[19].VOLUME,data[19].fiftyTwo_WH,data[19].fiftyTwo_WL,data[19].Date,data[19].Time]);
        GetStock.push([data[20].SYMBOL,data[20].OPEN,data[20].HIGH,data[20].LOW,data[20].PREVCLOSE,data[20].LTP,data[20].CHNG,data[20].CHANGPercentage,data[20].VOLUME,data[20].fiftyTwo_WH,data[20].fiftyTwo_WL,data[20].Date,data[20].Time]);
        GetStock.push([data[21].SYMBOL,data[21].OPEN,data[21].HIGH,data[21].LOW,data[21].PREVCLOSE,data[21].LTP,data[21].CHNG,data[21].CHANGPercentage,data[21].VOLUME,data[21].fiftyTwo_WH,data[21].fiftyTwo_WL,data[21].Date,data[21].Time]);
        GetStock.push([data[22].SYMBOL,data[22].OPEN,data[22].HIGH,data[22].LOW,data[22].PREVCLOSE,data[22].LTP,data[22].CHNG,data[22].CHANGPercentage,data[22].VOLUME,data[22].fiftyTwo_WH,data[22].fiftyTwo_WL,data[22].Date,data[22].Time]);
        GetStock.push([data[23].SYMBOL,data[23].OPEN,data[23].HIGH,data[23].LOW,data[23].PREVCLOSE,data[23].LTP,data[23].CHNG,data[23].CHANGPercentage,data[23].VOLUME,data[23].fiftyTwo_WH,data[23].fiftyTwo_WL,data[23].Date,data[23].Time]);
        GetStock.push([data[24].SYMBOL,data[24].OPEN,data[24].HIGH,data[24].LOW,data[24].PREVCLOSE,data[24].LTP,data[24].CHNG,data[24].CHANGPercentage,data[24].VOLUME,data[24].fiftyTwo_WH,data[24].fiftyTwo_WL,data[24].Date,data[24].Time]);
        GetStock.push([data[25].SYMBOL,data[25].OPEN,data[25].HIGH,data[25].LOW,data[25].PREVCLOSE,data[25].LTP,data[25].CHNG,data[25].CHANGPercentage,data[25].VOLUME,data[25].fiftyTwo_WH,data[25].fiftyTwo_WL,data[25].Date,data[25].Time]);
        GetStock.push([data[26].SYMBOL,data[26].OPEN,data[26].HIGH,data[26].LOW,data[26].PREVCLOSE,data[26].LTP,data[26].CHNG,data[26].CHANGPercentage,data[26].VOLUME,data[26].fiftyTwo_WH,data[26].fiftyTwo_WL,data[26].Date,data[26].Time]);
        GetStock.push([data[27].SYMBOL,data[27].OPEN,data[27].HIGH,data[27].LOW,data[27].PREVCLOSE,data[27].LTP,data[27].CHNG,data[27].CHANGPercentage,data[27].VOLUME,data[27].fiftyTwo_WH,data[27].fiftyTwo_WL,data[27].Date,data[27].Time]);
        GetStock.push([data[28].SYMBOL,data[28].OPEN,data[28].HIGH,data[28].LOW,data[28].PREVCLOSE,data[28].LTP,data[28].CHNG,data[28].CHANGPercentage,data[28].VOLUME,data[28].fiftyTwo_WH,data[28].fiftyTwo_WL,data[28].Date,data[28].Time]);
        GetStock.push([data[29].SYMBOL,data[29].OPEN,data[29].HIGH,data[29].LOW,data[29].PREVCLOSE,data[29].LTP,data[29].CHNG,data[29].CHANGPercentage,data[29].VOLUME,data[29].fiftyTwo_WH,data[29].fiftyTwo_WL,data[29].Date,data[29].Time]);
        GetStock.push([data[30].SYMBOL,data[30].OPEN,data[30].HIGH,data[30].LOW,data[30].PREVCLOSE,data[30].LTP,data[30].CHNG,data[30].CHANGPercentage,data[30].VOLUME,data[30].fiftyTwo_WH,data[30].fiftyTwo_WL,data[30].Date,data[30].Time]);
        GetStock.push([data[31].SYMBOL,data[31].OPEN,data[31].HIGH,data[31].LOW,data[31].PREVCLOSE,data[31].LTP,data[31].CHNG,data[31].CHANGPercentage,data[31].VOLUME,data[31].fiftyTwo_WH,data[31].fiftyTwo_WL,data[31].Date,data[31].Time]);
        GetStock.push([data[32].SYMBOL,data[32].OPEN,data[32].HIGH,data[32].LOW,data[32].PREVCLOSE,data[32].LTP,data[32].CHNG,data[32].CHANGPercentage,data[32].VOLUME,data[32].fiftyTwo_WH,data[32].fiftyTwo_WL,data[32].Date,data[32].Time]);
        GetStock.push([data[33].SYMBOL,data[33].OPEN,data[33].HIGH,data[33].LOW,data[33].PREVCLOSE,data[33].LTP,data[33].CHNG,data[33].CHANGPercentage,data[33].VOLUME,data[33].fiftyTwo_WH,data[33].fiftyTwo_WL,data[33].Date,data[33].Time]);
        GetStock.push([data[34].SYMBOL,data[34].OPEN,data[34].HIGH,data[34].LOW,data[34].PREVCLOSE,data[34].LTP,data[34].CHNG,data[34].CHANGPercentage,data[34].VOLUME,data[34].fiftyTwo_WH,data[34].fiftyTwo_WL,data[34].Date,data[34].Time]);
        GetStock.push([data[35].SYMBOL,data[35].OPEN,data[35].HIGH,data[35].LOW,data[35].PREVCLOSE,data[35].LTP,data[35].CHNG,data[35].CHANGPercentage,data[35].VOLUME,data[35].fiftyTwo_WH,data[35].fiftyTwo_WL,data[35].Date,data[35].Time]);
        GetStock.push([data[36].SYMBOL,data[36].OPEN,data[36].HIGH,data[36].LOW,data[36].PREVCLOSE,data[36].LTP,data[36].CHNG,data[36].CHANGPercentage,data[36].VOLUME,data[36].fiftyTwo_WH,data[36].fiftyTwo_WL,data[36].Date,data[36].Time]);
        GetStock.push([data[37].SYMBOL,data[37].OPEN,data[37].HIGH,data[37].LOW,data[37].PREVCLOSE,data[37].LTP,data[37].CHNG,data[37].CHANGPercentage,data[37].VOLUME,data[37].fiftyTwo_WH,data[37].fiftyTwo_WL,data[37].Date,data[37].Time]);
        GetStock.push([data[38].SYMBOL,data[38].OPEN,data[38].HIGH,data[38].LOW,data[38].PREVCLOSE,data[38].LTP,data[38].CHNG,data[38].CHANGPercentage,data[38].VOLUME,data[38].fiftyTwo_WH,data[38].fiftyTwo_WL,data[38].Date,data[38].Time]);
        GetStock.push([data[39].SYMBOL,data[39].OPEN,data[39].HIGH,data[39].LOW,data[39].PREVCLOSE,data[39].LTP,data[39].CHNG,data[39].CHANGPercentage,data[39].VOLUME,data[39].fiftyTwo_WH,data[39].fiftyTwo_WL,data[39].Date,data[39].Time]);
        GetStock.push([data[40].SYMBOL,data[40].OPEN,data[40].HIGH,data[40].LOW,data[40].PREVCLOSE,data[40].LTP,data[40].CHNG,data[40].CHANGPercentage,data[40].VOLUME,data[40].fiftyTwo_WH,data[40].fiftyTwo_WL,data[40].Date,data[40].Time]);
        GetStock.push([data[41].SYMBOL,data[41].OPEN,data[41].HIGH,data[41].LOW,data[41].PREVCLOSE,data[41].LTP,data[41].CHNG,data[41].CHANGPercentage,data[41].VOLUME,data[41].fiftyTwo_WH,data[41].fiftyTwo_WL,data[41].Date,data[41].Time]);
        GetStock.push([data[42].SYMBOL,data[42].OPEN,data[42].HIGH,data[42].LOW,data[42].PREVCLOSE,data[42].LTP,data[42].CHNG,data[42].CHANGPercentage,data[42].VOLUME,data[42].fiftyTwo_WH,data[42].fiftyTwo_WL,data[42].Date,data[42].Time]);
        GetStock.push([data[43].SYMBOL,data[43].OPEN,data[43].HIGH,data[43].LOW,data[43].PREVCLOSE,data[43].LTP,data[43].CHNG,data[43].CHANGPercentage,data[43].VOLUME,data[43].fiftyTwo_WH,data[43].fiftyTwo_WL,data[43].Date,data[43].Time]);
        GetStock.push([data[44].SYMBOL,data[44].OPEN,data[44].HIGH,data[44].LOW,data[44].PREVCLOSE,data[44].LTP,data[44].CHNG,data[44].CHANGPercentage,data[44].VOLUME,data[44].fiftyTwo_WH,data[44].fiftyTwo_WL,data[44].Date,data[44].Time]);
        GetStock.push([data[45].SYMBOL,data[45].OPEN,data[45].HIGH,data[45].LOW,data[45].PREVCLOSE,data[45].LTP,data[45].CHNG,data[45].CHANGPercentage,data[45].VOLUME,data[45].fiftyTwo_WH,data[45].fiftyTwo_WL,data[45].Date,data[45].Time]);
        GetStock.push([data[46].SYMBOL,data[46].OPEN,data[46].HIGH,data[46].LOW,data[46].PREVCLOSE,data[46].LTP,data[46].CHNG,data[46].CHANGPercentage,data[46].VOLUME,data[46].fiftyTwo_WH,data[46].fiftyTwo_WL,data[46].Date,data[46].Time]);
        GetStock.push([data[47].SYMBOL,data[47].OPEN,data[47].HIGH,data[47].LOW,data[47].PREVCLOSE,data[47].LTP,data[47].CHNG,data[47].CHANGPercentage,data[47].VOLUME,data[47].fiftyTwo_WH,data[47].fiftyTwo_WL,data[47].Date,data[47].Time]);
        GetStock.push([data[48].SYMBOL,data[48].OPEN,data[48].HIGH,data[48].LOW,data[48].PREVCLOSE,data[48].LTP,data[48].CHNG,data[48].CHANGPercentage,data[48].VOLUME,data[48].fiftyTwo_WH,data[48].fiftyTwo_WL,data[48].Date,data[48].Time]);
        GetStock.push([data[49].SYMBOL,data[49].OPEN,data[49].HIGH,data[49].LOW,data[49].PREVCLOSE,data[49].LTP,data[49].CHNG,data[49].CHANGPercentage,data[49].VOLUME,data[49].fiftyTwo_WH,data[49].fiftyTwo_WL,data[49].Date,data[49].Time]);
        if(funcNu==0){
            gsRun(client,GetStock)
        }
            if(funcNu==1){
                gsRun2(client,GetStock)
            }
            if(funcNu==2){
                gsRun4(client,GetStock)
            }
    } catch (error) {
        console.log("243: Error While Converting data",error);
    }
} 
 //insert into sheet 2
async function gsRun2(client,stocksData){
try {
    const gsApi = google.sheets({version:'v4',auth:client});
    const updateOption1= {
    spreadsheetId:'1iA8gKAehpYPaI8XMb5PhE6dFs0HTxNohZQHizScRk84', // spreadsheetId
    range: 'Data2!A2',
    valueInputOption:'USER_ENTERED',
    resource: {values:stocksData}
};
let res1 = await gsApi.spreadsheets.values.update(updateOption1); // post
console.log("257: >>>> Sheet 2 updated",res1.status);  
} catch (error) {
    console.log('259:ERROR While Updating Sheet 2',error);
}
}
     //insert into sheet 3
async function gsRun4(client,stocksData){
try {
    const gsApi = google.sheets({version:'v4',auth:client});
    const updateOption1= {
        spreadsheetId:'1iA8gKAehpYPaI8XMb5PhE6dFs0HTxNohZQHizScRk84', // spreadsheetId
        range: 'Data3!A2',
        valueInputOption:'USER_ENTERED',
        resource: {values:stocksData}
    };
    let res1 = await gsApi.spreadsheets.values.update(updateOption1); // post
    console.log("273: >>>> Sheet 3 updated",res1.status);
} catch (error) {
    console.log('275: ERROR While Updating Sheet 3',error);
    }
}

module.exports={main}