module.exports = {
  url:"http://localhost:9000",
  // url: "https://api.niftyleveltracker.in",
  mainFunctionTimer: 120000,//120000 for every 2min  call main function
  sheet2UpdateTime:10,
  sheet3UpdateTime:20,
  indexSymbol: "^NSEI",
  first20Symbols:
    "TCS.NS,ONGC.NS,BAJAJFINSV.NS,UPL.NS,BAJFINANCE.NS,SBILIFE.NS,BPCL.NS,ITC.NS,HINDALCO.NS,JSWSTEEL.NS,BAJAJ-AUTO.NS,KOTAKBANK.NS,COALINDIA.NS,M&M.NS,TATAMOTORS.NS,INFY.NS,EICHERMOT.NS,TATASTEEL.NS,TECHM.NS,RELIANCE.NS",
    second20Symbols:
    "NESTLEIND.NS,INDUSINDBK.NS,LT.NS,BRITANNIA.NS,BHARTIARTL.NS,ULTRACEMCO.NS,DRREDDY.NS,HCLTECH.NS,TATACONSUM.NS,ADANIENT.NS,HEROMOTOCO.NS,HDFCBANK.NS,WIPRO.NS,NTPC.NS,MARUTI.NS,TITAN.NS,DIVISLAB.NS,ICICIBANK.NS,ADANIPORTS.NS,ASIANPAINT.NS,CIPLA.NS,AXISBANK.NS,SBIN.NS,GRASIM.NS,SUNPHARMA.NS,APOLLOHOSP.NS,HINDUNILVR.NS,POWERGRID.NS,HDFCLIFE.NS,LTIM.NS",
};
